id: P003245
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG3993
  title: དཔལ་འབྲི་གུང་བཀའ་བརྒྱུད་ཀྱི་བསང་གསེར་སྐྱེམས་བཅས།
  author: ''
  volumes:
    455605924d9e4154a853d6fc2ebe9a1f:
      image_group_id: I1KG4058
      title: ''
      volume_number: 1
      total_pages: 468
