id: I1C767FED
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-31T02:09:28+00:00'
last_modified: '2022-06-07T18:37:24.957663+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG3993
  title: དཔལ་འབྲི་གུང་བཀའ་བརྒྱུད་ཀྱི་བསང་གསེར་སྐྱེམས་བཅས།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    D046:
      image_group_id: I1KG4058
      title: ''
      total_pages: 468
      order: 1
      base_file: D046.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
